apiVersion: apps/v1
kind: Deployment
metadata:
        name: sysbench-64
spec:
        replicas: 64
        selector:
                matchLabels:
                        app: sysbench
        template:
                metadata:
                        name: sysbench
                        labels:
                                app: sysbench
                spec:
                        containers:
                        - name: sysbench
                          image: severalnines/sysbench
                          command:
                                - sysbench
                                - --test=cpu
                                - --cpu-max-prime=2000000000
                                - --forced-shutdown=0
                                - --threads=1
                                - --time=600
                                - run
